name: Deploy to Amazon ECS result

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lks-voting-image
  ECS_SERVICE: lks-result-service
  ECS_CLUSTER: lks-voting-cluster
  ECS_TASK_DEFINITION: lks-td-result
  ACCOUNT_ID: 214365501455


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        
        docker build -t ${{ env.ECR_REPOSITORY }}:result-latest ./result
        docker tag ${{ env.ECR_REPOSITORY }}:result-latest ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:result-${{ github.sha }}
        docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:result-${{ github.sha }}

    - name: Update image in taskdef.json
      run: |
        sed -i "s|IMAGE_URI|${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:result-${{ github.sha }}|g" /result/task-definition.json

    - name: Register task definition
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://result/task-definition.json

    - name: Update service
      run: |
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --task-definition ${{ env.ECS_TASK_DEFINITION }} \
          --force-new-deployment

    - name: Publish Message To SNS Subscribers
      env:
        TOPIC_ARN: ${{ secrets.AWS_SNS_ARN }}
      run: aws sns publish --topic-arn $TOPIC_ARN --subject "Hello, from Indonesia" --message "New Version Is Released"
